import type { Metadata } from "next";
import { Roboto } from "next/font/google"; 
import "./style/globals.css"; 
import { CartProvider } from "@/app/context/CartContext"; 

const roboto = Roboto({
  weight: ["400", "700"], 
  subsets: ["latin"],
  variable: "--font-roboto", 
});

export const metadata: Metadata = {
  title: "JB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
